### ISSUE TITLE
Segmentation fault on file_browser

### ISSUE THREAD

**Issue by Georacer** [marvinkreis/rofi-plugins#6]
Hello,

I am in Ubuntu 18.04.1 LTS, with rofi 1.5.0, installed from apt.

I have installed the plugins manually, and used `libtool` to place it in the `/usr/lib/x86_64-linux-gnu/rofi/`.

I launch file_browser with 
`rofi -show file_browser -show-icons`
I get
```bash
Mode file_browser is not enabled. I have enabled it for now.
Please consider adding file_browser to the list of enabled modi: modi: window,run,ssh,file_browser.
```
So far so good.

But then, when I navigate in ~/Desktop, it crashes with
```bash
Segmentation fault (core dumped)
```

Tell me if I can provide with more information.

P.S.
I don't seem to understand the `:cmd` syntax to open a directory or file. Can you provide an example?

Thanks in advance

**Comment by Georacer** [comment]
I have pulled master, recompiled and re-installed. I confirm that I can navigate without core dumps (so far).
Thanks for that!

Regarding `:<cmd>`: I couldn't understand its usage because entering `:<cmd` in the prompt didn't have any kind of effect. Only after I accidentally hit enter again on the file and it opened with `<cmd>` did I realize what was going on.

I suggest (if you feel like it and agree):
EITHER: emphasize in documentation that `:<cmd>` is a _state change/ augmenting command_ and doesn't have an immediate effect.
OR: If you don't want `:<cmd>` to affect all future file opens, have the selected file immediately open with `<cmd>' upon hitting `:<cmd>`.

Thanks for your work!

**Comment by marvinkreis** [comment]
I agree that the `:<cmd>` stuff is a bit weird. I think I could change it so the user can select a file with `Shift+Enter` and is then prompted with which program to open the file.

**Comment by Georacer** [comment]
The new `:cmd` interface works fine. I have set `nautilus` the default in the launching command and `Shift+Enter` for custom programs works fine.
