### ISSUE TITLE
Feature request: Separate hidden file shortkeys

### ISSUE THREAD

**Issue by Georacer** [marvinkreis/rofi-plugins#7]
I'd like to add file_browser plugin to the rest of the modi of my regular rofi launch command.
But as soon as I get to this modi, it captures `shift+left/right` to show/hide hidden files and can't navigate to other modi anymore.

Could a separate shortkey for hidden files be added (e.g. `shift+up/down`)?

**Comment by marvinkreis** [comment]
Hi, thanks for the suggestion.

Unfortunately I can only use keybindings defined by rofi (which is why I was using the mode-switch keybindings). I'll change it to `Alt+1`, which is one of the keybindings that rofi defines for custom actions.

**Comment by marvinkreis** [comment]
Some other options:
1. Use `Ctrl+Enter` to toggle hidden files, but this only works the input field is empty
2. Use `Shift+Right` to enable hidden files, but switch to the next mode if hidden files are already enabled (and the other way around for `Shift+Left`) 

I think the most sensible way is to implement both, use (1) as default, and add a command line option to use (2).

**Comment by Georacer** [comment]
Sounds great!

I'm not sure if you have implemented this already, but a cmd option to
enable hidden files would complement this nicely, I think.

**Comment by Georacer** [comment]
I like the new API. I disabled hidden files by default and toggling them with `ctrl+space` is straightforward.
