### ISSUE TITLE
Space in folder name results in buggy behaviour

### ISSUE THREAD

**Issue by Georacer** [marvinkreis/rofi-plugins#8]
I found another bug in `file_browser` today, sorry if I start looking pedantic.
If navigating in a path containing a space, file opening behaviour is erratic.

Steps to reproduce:
1. Create path and file:
```bash
:~$ mkdir test\ folder
:~$ cd test\ folder/
:~/test folder$ touch test_file.txt
:~/test folder$ echo "example content" >> test_file.txt 
:~/test folder$ cat test_file.txt 
example content
```
2. Launch file_browser and select `gedit` to open files:
![rofi-2018-09-27-1956-00000](https://user-images.githubusercontent.com/3149996/46162170-2a909e00-c290-11e8-8d8e-5671f48a4b7c.png)
3. Navigate to directory and select file:
![rofi-2018-09-27-1957-00000](https://user-images.githubusercontent.com/3149996/46162186-37ad8d00-c290-11e8-9a79-bb6ca064f1f7.png)
4. `gedit` opens two files and none of them is the correct one:
![screenshot from 2018-09-27 19-57-30](https://user-images.githubusercontent.com/3149996/46162204-45631280-c290-11e8-9701-e9adc1b99601.png)

**Comment by marvinkreis** [comment]
Yeah, I noticed that as well while fixing the other stuff.
I have a fix for this already, I'll push it soon.

Don't worry about opening too many issues, I appreciate the feedback.

**Comment by Georacer** [comment]
Tested and working fine!
