### ISSUE TITLE
Weird padding issue

### ISSUE THREAD

**Issue by A1phaZer0** [marvinkreis/rofi-plugins#9]
Hi, there is a padding issue in file_browser.

rofi config is : [config](https://github.com/A1phaZer0/dotfiles-bspwm/blob/master/rofi/config)

![2018-10-02-001016_1920x1080_scrot](https://user-images.githubusercontent.com/8542998/46302736-76b74780-c5dc-11e8-8133-46a564460072.png)

**Comment by marvinkreis** [comment]
Hi,
Sorry that I didn't answer this earlier, somehow GitHub didn't notify me about this issue.

I can reproduce the problem with your config, however this doesn't seem to be a problem with the plugin, but rather with rofi's message line. `echo "This should be the first line" | rofi -dmenu -mesg "This is a test status"` gave me the same result.

I tried commenting out settings in your config, and it seems that either removing `rofi.padding` or `rofi-fullscreen` gets rid of the problem. You can also use the file browser with `-fb_disable_status` to get rid of the status message for now.
